### ISSUE TITLE
Error: Unbound module Fields

### ISSUE THREAD

**Issue by agarwal** [janestreet/ppx_xml_conv#1]
```
$ cat foo.ml
type t = {a:int; b:string} [@@deriving xml]

$ ocamlfind ocamlc -package ppx_xml_conv -c foo.ml
findlib: [WARNING] Interface main.cmi occurs in several directories: ., ~/.opam/4.02.3/lib/ocaml/compiler-libs
File "foo.ml", line 1, characters 0-43:
Error: Unbound module Fields
```

I checked Fieldslib and it only has `Field`, not `Fields`. Many of the ppx_*_conv packages seem to be missing ocamlfind dependencies, e.g. see also janestreet/ppx_sexp_conv#1.

**Comment by ghost** [comment]
The `Fields` module comes from `[@@deriving fields]`, from ppx_fields_conv. However I think ppx_xml_conv suffers from the same problem as ppx_csv_conv: janestreet/ppx_csv_conv#1, i.e. the runtime lib for ppx_xml_conv is missing. Sorry for that, we are currently reworking our public release process which will make it easier for us to provide fixes quicker.

**Comment by agarwal** [comment]
Got it. Thanks.

Just in case anyone else gets to this issue, note there's no manual workaround for now because this lib also ends up depending on the unreleased `csvfields` mentioned in the other issue.

**Comment by vbmithr** [comment]
Not working with the `ppx-driver` method. I think there is 2 issues:

* Impossible to generate the `Fields` module before the XML code, no matter how I try, I always end up with having the XML code generated before the Fields module.

* When the type has a name, the generated module is `Fields_of_name`, whereas the generated XML code requires module `Fields`

**Comment by vbmithr** [comment]
Ok, actually

```ocaml
type t = {
  a : string ;
} [@@deriving xml,fields]
```
works, but fails if `t` has any other name. Still a bug :p

**Comment by hhugo** [comment]
It seems to be working now and gives better error messages: 
```
type t = {a:int; b:string} [@@deriving xml];;
Error: Deriver fields is needed for xml, you need to add it before in the list
```
